@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Диаграмма компонентов: Device Orchestrator Service

Container_Boundary(deviceOrchestrator, "Device Orchestrator") {
    Component(api, "Command API", "Spring Web", "REST/gRPC интерфейс")
    Component(processor, "Command Processor", "Kotlin", "Трансформация команд")
    Component(ruleEngine, "Rule Engine", "Drools", "Валидация правил")
    Component(stateCache, "State Cache", "Redis", "Кэш состояний")
    Component(kafkaProducer, "Event Producer", "Spring Kafka", "Публикация событий")
}

Rel(api, processor, "Передает команды", "CommandDTO")
Rel(processor, ruleEngine, "Проверяет правила", "")
Rel(processor, stateCache, "Проверяет состояние", "JSON")
Rel(processor, kafkaProducer, "Публикует события", "Avro")

Rel_R(api, apiGateway, "Получает запросы", "gRPC")
Rel_L(kafkaProducer, kafka, "Отправляет события", "DeviceEvent")
@enduml